/* Zianna Land Phase 3 — controlled character conversations and family coaching. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const PROGRAM=window.ZL_PROGRAM, READERS=window.ZL_READERS||[], DIALOGUES=window.ZL_DIALOGUES||[], UNITS=PROGRAM.weeks.flatMap(w=>w.units), STORE='zl_phase1_state';
const blankState={profile:null,records:{},reading:{},dialogues:{},daily:{},activity:[],lastView:'home'};
let state=loadState(),current=null,currentMode='new',challengePassed=false,challengePoints=0,spoken=false,challengeAttempts=0;
let mediaRecorder=null,recordChunks=[],installPrompt=null,currentReader=null,readerPassed=false,readerFilter='all',currentTalk=null,talkTurn=0,talkResults=[],speechRecognition=null;

function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORE)||'{}');return {...blankState,...saved,records:saved.records||{},reading:saved.reading||{},dialogues:saved.dialogues||{},daily:saved.daily||{},activity:saved.activity||[]}}catch{return {...blankState}}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function day(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function daysBetween(a,b=day()){return Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
const voicePlayer=new Audio();voicePlayer.preload='auto';let voiceRequest=0;
function deviceSpeak(text,rate=.86){if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){toast('自然发音暂时没有加载，请检查网络后再试');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate;const voices=speechSynthesis.getVoices(),preferred=voices.find(v=>/^en-US$/i.test(v.lang)&&/Natural|Premium|Online/i.test(v.name))||voices.find(v=>/^en(-|_)/i.test(v.lang));if(preferred)u.voice=preferred;speechSynthesis.speak(u)}
function speak(text,rate=.86){const request=++voiceRequest;voicePlayer.pause();voicePlayer.removeAttribute('src');if('speechSynthesis' in window)speechSynthesis.cancel();const parts=(text.match(/[^.!?]+[.!?]?/g)||[text]).map(x=>x.trim()).filter(Boolean);let index=0;const fallback=()=>{if(request===voiceRequest)deviceSpeak(parts.slice(index).join(' '),rate)};const playNext=()=>{if(request!==voiceRequest||index>=parts.length)return;const part=parts[index++],url=`https://dict.youdao.com/dictvoice?audio=${encodeURIComponent(part)}&le=eng&type=2`;voicePlayer.src=url;voicePlayer.playbackRate=Math.max(.8,Math.min(1.1,rate/.86));voicePlayer.onerror=fallback;voicePlayer.onended=playNext;const play=voicePlayer.play();if(play?.catch)play.catch(fallback)};playNext()}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1900)}
function unitIndex(id){return UNITS.findIndex(u=>u.id===id)}
function weekFor(unit){return PROGRAM.weeks[unit.week-1]}
function startIndex(){return state.profile?.level==='Explorer'?40:state.profile?.level==='Sprout'?20:0}
function nextUnit(){return UNITS.slice(startIndex()).find(u=>!state.records[u.id]?.mastered)}
function skillAverage(skill){const rows=state.activity.filter(x=>x.skill===skill).slice(-5);return rows.length?rows.reduce((n,x)=>n+x.score,0)/rows.length:100}
function adaptiveMode(){const rows=state.activity.slice(-5);if(!rows.length)return 'standard';const avg=rows.reduce((n,x)=>n+x.score,0)/rows.length;if(avg<75||rows.at(-1)?.mastered===false)return 'guided';if(rows.length>=3&&avg>=93&&rows.slice(-3).every(x=>x.mastered))return 'stretch';return 'standard'}
function adaptiveCopy(){return {guided:'陪伴模式 · 精简选项并保留中文提示',standard:'稳步模式 · 按当前节奏继续成长',stretch:'挑战模式 · 先独立理解，再查看中文提示'}[adaptiveMode()]}
function dueReview(){return UNITS.filter(u=>{const r=state.records[u.id];if(!r?.mastered)return false;const reviews=r.reviews||[],target=PROGRAM.reviewIntervals[reviews.length];return target&&daysBetween(r.completedAt)>=target&&!reviews.includes(day())}).sort((a,b)=>skillAverage(a.skills[0])-skillAverage(b.skills[0]))[0]}
function todayPlan(){const today=day(),review=dueReview();let assigned=UNITS.find(u=>u.id===state.daily[today]);if(!assigned){assigned=nextUnit();if(assigned){state.daily[today]=assigned.id;saveState()}}const list=[];if(review)list.push({unit:review,mode:'review'});if(assigned&&assigned.id!==review?.id)list.push({unit:assigned,mode:state.records[assigned.id]&&!state.records[assigned.id].mastered?'support':'new'});return list.length?list:[{unit:UNITS.at(-1),mode:'practice'}]}
function planDone(item){const r=state.records[item.unit.id];if(item.mode==='review')return r?.reviews?.includes(day());return r?.lastDone===day()}
function isUnlocked(unit){const i=unitIndex(unit.id),frontier=unitIndex(nextUnit()?.id);return i<startIndex()||frontier<0||i<=frontier}

function nav(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));const navName=name==='coach'?'dialogue':name;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===navName));if(!['lesson','reader','coach'].includes(name))state.lastView=name;saveState();if(name==='home'){renderHome();renderCoachCard()}if(name==='course')renderCourse();if(name==='dialogue')renderDialogueHub();if(name==='library')renderLibrary();if(name==='parent')renderReport();scrollTo({top:0,behavior:'auto'})}
function levelName(){return PROGRAM.levels.find(l=>l.id===state.profile?.level)?.name||'等待测评'}

function activeWeek(){const u=nextUnit()||UNITS.at(-1);return weekFor(u)}
function renderHome(){const plan=todayPlan(),done=plan.filter(planDone).length,pct=Math.round(done/plan.length*100),w=activeWeek(),weekDone=w.units.filter(u=>state.records[u.id]?.mastered).length,projectReady=weekDone>=4;$('#levelPill').textContent=`${levelName()}阶段`;$('#todayCount').textContent=`${done} / ${plan.length}`;$('#todayPercent').textContent=`${pct}%`;$('#todayRing').style.setProperty('--p',pct);$('#todayHint').textContent=done===plan.length?'今天的学习已经完成，可以去成长地图自由探索。':plan.some(x=>x.mode==='review')?'先完成到期复习，再开启今天的新课。':'完成一节新课，让英语能力继续生长。';$('#adaptiveSummary').textContent=adaptiveCopy();$('#worldStory').innerHTML=`<p class="eyebrow">STORY TREE · CHAPTER ${w.units[0].week}</p><h3>${w.chapter}</h3><p>${w.dialogue}</p><div class="clue-line"><span>本周线索</span><b>${w.clue}</b></div><button class="text-link" data-world-unit="${w.units[0].id}">进入本周故事 →</button>`;$('#weeklyProject').innerHTML=`<p class="eyebrow">WEEKLY CREATION</p><h3>${w.name}作品</h3><p>${w.project}</p><div class="project-status ${projectReady?'ready':''}">${projectReady?'已经解锁 · 可以创作':'完成前 4 课后解锁'} · ${weekDone}/5</div><button class="btn ${projectReady?'btn-primary':'btn-soft'}" data-project-unit="${w.units[4].id}" ${projectReady?'':'disabled'}>${projectReady?'开始我的作品':'继续学习来解锁'}</button>`;$('#dailyPath').innerHTML=plan.map((item,i)=>{const r=state.records[item.unit.id],doneNow=planDone(item),label=item.mode==='review'?'到期复习':item.mode==='support'?'巩固练习':item.mode==='practice'?'自由练习':'今日新课';return `<button class="daily-card ${doneNow?'done':''}" data-daily="${item.unit.id}" data-mode="${item.mode}"><span class="num">0${i+1}</span><span class="tag">${label} · ${item.unit.minutes} MIN</span><h3>${item.unit.title}</h3><p>${item.unit.goal}</p><span class="mastery">${r?`${r.score}% · ${r.mastered?'已经掌握':'继续生长'}`:'开始学习'} →</span></button>`}).join('');$$('[data-daily]').forEach(b=>b.onclick=()=>openLesson(b.dataset.daily,b.dataset.mode));$('[data-world-unit]').onclick=e=>openLesson(e.currentTarget.dataset.worldUnit,state.records[e.currentTarget.dataset.worldUnit]?'practice':'new');const project=$('[data-project-unit]');if(project&&!project.disabled)project.onclick=e=>openLesson(e.currentTarget.dataset.projectUnit,state.records[e.currentTarget.dataset.projectUnit]?'practice':'new')}

function renderCourse(){$('#levelStrip').innerHTML=PROGRAM.levels.map(l=>`<article class="level-card"><strong>${l.name} · ${l.range}</strong><small>${l.goal}</small></article>`).join('');$('#weekList').innerHTML=PROGRAM.weeks.map((w,wi)=>{const mastered=w.units.filter(u=>state.records[u.id]?.mastered).length,pct=mastered*20;return `<article class="week"><div class="week-side"><span class="week-no">W${String(wi+1).padStart(2,'0')}</span><h3>${w.name}</h3><p>${w.goal}</p><div class="bar"><span style="width:${pct}%"></span></div><p>${mastered} / 5 已掌握 · ${w.level}</p></div><div class="unit-list">${w.units.map(u=>{const r=state.records[u.id],locked=!isUnlocked(u);return `<button class="unit ${r?.mastered?'mastered':''} ${locked?'locked':''}" data-unit="${u.id}" ${locked?'aria-disabled="true"':''}><small>DAY ${u.day} · ${u.kind}</small><strong>${u.title}</strong><span>${r?`${r.score}% ${r.mastered?'已掌握':'待巩固'}`:locked?'完成前一课后解锁':u.goal}</span></button>`}).join('')}</div></article>`}).join('');$$('[data-unit]').forEach(b=>b.onclick=()=>{const u=UNITS.find(x=>x.id===b.dataset.unit);if(!isUnlocked(u))return toast('先完成前面的课程，这条小路就会打开');openLesson(u.id,state.records[u.id]?'practice':'new')})}

function openLesson(id,mode='new'){current=UNITS.find(u=>u.id===id);if(!current)return;const origin=document.querySelector('.view.active')?.id.replace('view-','');state.lastView=['course','library'].includes(origin)?origin:'home';currentMode=mode;challengePassed=false;challengePoints=0;spoken=false;challengeAttempts=0;nav('lesson');const week=weekFor(current),adaptive=adaptiveMode();$('#lessonEyebrow').textContent=`WEEK ${current.week} · ${week.name} · ${mode==='review'?'复习':mode==='support'?'巩固':'学习'}`;$('#lessonTitle').textContent=current.title;$('#lessonGoal').textContent=current.goal;$('#lessonStep').textContent=`DAY ${current.day} / 5`;$('#adaptiveLabel').textContent=adaptiveCopy().split(' · ')[0];$('#adaptiveLabel').dataset.mode=adaptive;$('#worldChapter').textContent=`第 ${current.week} 章 · ${week.chapter}`;$('#worldDialogue').textContent=`“${week.dialogue}” — ${week.guide}`;$('#lessonWords').innerHTML=current.words.map((w,i)=>`<button class="word" data-word="${i}">${w[0]}<small>${w[1]}</small></button>`).join('');$$('[data-word]').forEach(b=>b.onclick=()=>speak(current.words[+b.dataset.word][0]));$('#lessonStory').textContent=current.story;$('#lessonCn').textContent=current.cn;$('#lessonCn').hidden=adaptive==='stretch';$('#toggleLessonCn').textContent=adaptive==='stretch'?'显示中文提示':'隐藏中文提示';$('#speakPrompt').textContent=current.day===5?`${week.project} ${current.speakPrompt}`:current.speakPrompt;$('#recordMessage').textContent='';$('#recordPreview').hidden=true;$('#finishLesson').disabled=true;$('#markSpoken').textContent='我已经说了一遍';renderVideo();renderChallenge();scrollTo({top:0,behavior:'auto'})}
async function renderVideo(){const v=$('#lessonVideo'),fallback=$('#videoFallback'),video=current.video;v.pause();v.removeAttribute('src');v.replaceChildren();v.load();if(!video){$('#videoBlock').hidden=true;return}$('#videoBlock').hidden=false;fallback.hidden=false;fallback.innerHTML='正在准备兼容视频…<br><small>视频将在本页播放，不会跳转</small>';$('#videoCredit').textContent=`${video.credit} · ${video.license}`;$('#videoCredit').href=video.page;let sources=[];if(video.file){try{const api=`https://commons.wikimedia.org/w/api.php?action=query&format=json&origin=*&prop=videoinfo&viprop=url%7Cderivatives&titles=File:${encodeURIComponent(video.file)}`,data=await fetch(api).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}),page=Object.values(data.query?.pages||{})[0],items=page?.videoinfo?.[0]?.derivatives||[];const compatible=items.filter(x=>x.src&&(/quicktime|mp4/i.test(x.type||'')||/\.mp4(?:\?|$)/i.test(x.src)));compatible.sort((a,b)=>{const ar=Math.abs((a.height||360)-360),br=Math.abs((b.height||360)-360);return ar-br});sources=compatible.map(x=>({src:x.src,type:x.type||'video/mp4'}))}catch{sources=[]}}sources.push({src:video.src,type:'video/webm'});const seen=new Set();sources.filter(x=>x.src&&!seen.has(x.src)&&seen.add(x.src)).forEach(x=>{const source=document.createElement('source');source.src=x.src;source.type=x.type;v.append(source)});v.load()}

function renderChallenge(){const area=$('#challengeArea'),type=current.template;$('#challengeResult').textContent='';const titles={listen:'听音选答案',match:'中英文配对',sound:'发现声音规律',build:'把词语搭成句子',sequence:'排出故事顺序',speak:'听懂后准备表达'};$('#challengeTitle').textContent=`② ${titles[type]}`;if(type==='listen'||type==='speak')renderChoice(type);if(type==='match')renderMatch();if(type==='sound')renderSound();if(type==='build')renderBuild();if(type==='sequence')renderSequence()}
function passChallenge(points,msg='完成得很好！'){challengePassed=true;challengePoints=Math.max(challengePoints,points);$('#challengeResult').textContent=msg;updateFinish()}
function scoreForAttempt(){return challengeAttempts<=1?65:challengeAttempts===2?50:40}
function renderChoice(type){$('#challengeHelp').textContent=type==='listen'?'先点“听问题”，再选择答案。':'听核心句，选择它所在的本周主题。';let options=type==='listen'?[...current.options]:[weekFor(current).name,'天气观察员','校园好帮手'];if(adaptiveMode()==='guided')options=options.filter((x,i)=>i===0||x===(type==='listen'?current.answer:weekFor(current).name)).slice(0,2);$('#challengeArea').innerHTML=`<button class="btn btn-soft" id="playQuestion">♪ 听一遍</button><div class="choice-grid">${options.map((o,i)=>`<button class="choice" data-choice="${i}">${o}</button>`).join('')}</div>`;$('#playQuestion').onclick=()=>speak(type==='listen'?current.question:current.pattern);$$('[data-choice]').forEach(b=>b.onclick=()=>{challengeAttempts++;const value=options[+b.dataset.choice],ok=type==='listen'?value===current.answer:value===weekFor(current).name;$$('[data-choice]').forEach(x=>x.classList.remove('wrong'));if(ok){b.classList.add('correct');passChallenge(scoreForAttempt())}else{b.classList.add('wrong');$('#challengeResult').textContent='再听一次，找找句子里的线索。'}})}
function renderMatch(){const pairs=current.words.slice(0,3),items=[...pairs.map(x=>({side:'en',v:x[0],pair:x[0]})),...pairs.map(x=>({side:'cn',v:x[1],pair:x[0]}))].sort((a,b)=>a.v.localeCompare(b.v));let selected=null,matched=new Set();$('#challengeHelp').textContent='先选一个英文，再选对应的中文。';$('#challengeArea').innerHTML=`<div class="match-grid">${items.map((x,i)=>`<button class="match-item" data-mi="${i}">${x.v}</button>`).join('')}</div>`;$$('[data-mi]').forEach(b=>b.onclick=()=>{if(b.classList.contains('correct'))return;const item=items[+b.dataset.mi];if(!selected){selected={b,item};b.classList.add('selected');return}if(selected.item.side!==item.side&&selected.item.pair===item.pair){selected.b.classList.replace('selected','correct');b.classList.add('correct');matched.add(item.pair);selected=null;if(matched.size===pairs.length)passChallenge(scoreForAttempt(),'三组都配对成功！')}else{challengeAttempts++;selected.b.classList.remove('selected');selected={b,item};b.classList.add('selected');$('#challengeResult').textContent='这两个还不是一对，再看看。'}})}
function renderSound(){$('#challengeHelp').textContent='找出今天要发现的拼读线索。';const opts=[current.phonics,'短元音 o · hot / dog','字母组合 th · this / that'];$('#challengeArea').innerHTML=`<div class="choice-grid">${opts.map((o,i)=>`<button class="choice" data-sound="${i}">${o}</button>`).join('')}</div>`;$$('[data-sound]').forEach(b=>b.onclick=()=>{challengeAttempts++;if(+b.dataset.sound===0){b.classList.add('correct');speak(current.phonics.split('·')[1]||current.pattern);passChallenge(scoreForAttempt())}else{b.classList.add('wrong');$('#challengeResult').textContent='看看本周关键词里反复出现的声音。'}})}
function renderBuild(){let answer=[];const tokens=[...current.build].reverse();$('#challengeHelp').textContent='按正确顺序点击词语，搭出核心句。';$('#challengeArea').innerHTML=`<div class="answer-line" id="answerLine"></div><div class="token-bank">${tokens.map((t,i)=>`<button class="token" data-token="${i}">${t}</button>`).join('')}</div><button class="btn btn-outline" id="resetBuild" style="margin-top:12px">重新排列</button>`;const draw=()=>{$('#answerLine').textContent=answer.join(' ');if(answer.length===current.build.length){challengeAttempts++;if(answer.join(' ')===current.build.join(' '))passChallenge(scoreForAttempt(),'句子搭好了！点核心句听一遍。');else $('#challengeResult').textContent='顺序还差一点，重新排列试试。'}};$$('[data-token]').forEach(b=>b.onclick=()=>{if(b.disabled)return;answer.push(tokens[+b.dataset.token]);b.disabled=true;draw()});$('#resetBuild').onclick=()=>renderChallenge()}
function renderSequence(){let order=[];const items=[...current.sequence].reverse();$('#challengeHelp').textContent='按故事发生的顺序点击句子。';$('#challengeArea').innerHTML=`<div class="answer-line" id="sequenceAnswer">等待第一步…</div><div class="sequence-list">${items.map((x,i)=>`<button class="sequence-item" data-seq="${i}"><b>${i+1}</b>${x.text}</button>`).join('')}</div><button class="btn btn-outline" id="resetSequence" style="margin-top:12px">重新排列</button>`;$$('[data-seq]').forEach(b=>b.onclick=()=>{if(b.disabled)return;const item=items[+b.dataset.seq];order.push(item);b.disabled=true;$('#sequenceAnswer').textContent=order.map(x=>x.text).join(' ');if(order.length===items.length){challengeAttempts++;if(order.every((x,i)=>x.id===i))passChallenge(scoreForAttempt(),'故事顺序完全正确！');else $('#challengeResult').textContent='故事顺序还需要调整，再读一遍。'}});$('#resetSequence').onclick=()=>renderChallenge()}

function updateFinish(){$('#finishLesson').disabled=!(challengePassed&&spoken)}
function markSpoken(){spoken=true;$('#recordMessage').textContent='已经完成一次开口表达。';$('#markSpoken').textContent='已完成 ✓';updateFinish()}
async function recordWork(){if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){toast('当前浏览器不能录音，可以完成跟读确认');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>recordChunks.push(e.data);mediaRecorder.onstop=async()=>{const blob=new Blob(recordChunks,{type:mediaRecorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);$('#recordPreview').src=url;$('#recordPreview').hidden=false;$('#recordWork').textContent='重新录制';$('#recordWork').classList.remove('recording');stream.getTracks().forEach(t=>t.stop());await saveArtifact({id:`${current.id}-${Date.now()}`,unitId:current.id,week:current.week,date:day(),title:`${weekFor(current).name} · ${current.title}`,blob});spoken=true;$('#recordMessage').textContent='声音作品已经保存在这台设备。';updateFinish()};mediaRecorder.start();$('#recordWork').textContent='停止并保存';$('#recordWork').classList.add('recording');$('#recordMessage').textContent='正在录音…'}catch{$('#recordMessage').textContent='没有获得麦克风权限，可以用“我已经说了一遍”。'}}

function finishLesson(){const total=challengePoints+35,mastered=total>=PROGRAM.masteryThreshold,today=day(),old=state.records[current.id]||{},reviews=old.reviews||[];if(currentMode==='review'&&!reviews.includes(today))reviews.push(today);state.records[current.id]={...old,score:Math.max(old.score||0,total),mastered:old.mastered||mastered,completedAt:old.completedAt||today,lastDone:today,reviews,attempts:(old.attempts||0)+1};state.activity.push({date:today,unitId:current.id,week:current.week,skill:current.skills[0],score:total,mastered,minutes:current.minutes,mode:currentMode});saveState();toast(mastered?'已经掌握，成长地图前进啦！':'完成练习，系统会安排一次巩固');setTimeout(()=>nav('home'),650)}

const assessment=[
  {q:'听一听，哪个词表示“有风的”？',say:'windy',options:['rainy','windy','sunny'],a:1},
  {q:'Which animal can fly?',options:['A fox','A fish','A bird'],a:2},
  {q:'哪个词和 tree 有相同的长元音？',options:['red','green','cat'],a:1},
  {q:'读一读：Mia takes an umbrella. Mia 拿了什么？',options:['An umbrella','A pencil','A flower'],a:0},
  {q:'哪个句子正确表达“我会游泳”？',options:['I am swim.','I can swim.','I swim can.'],a:1},
  {q:'先自己读：I can see a bright Moon. 读完后选择最接近的感受。',say:'I can see a bright Moon.',options:['我能独立读出来','我需要听一遍再读','我还不会'],a:0}
];
let assessIndex=0,assessScore=0,assessChoice=null;
function startAssessment(){assessIndex=0;assessScore=0;assessChoice=null;$('#assessmentLayer').hidden=false;renderAssessment()}
function renderAssessment(){const box=$('#assessmentContent');$('#assessBar').style.width=`${assessIndex/assessment.length*100}%`;if(assessIndex>=assessment.length)return finishAssessment();const q=assessment[assessIndex];box.innerHTML=`<p class="eyebrow">第 ${assessIndex+1} / ${assessment.length} 题</p><h3>${q.q}</h3>${q.say?'<button class="btn btn-soft" id="assessListen">♪ 听单词</button>':''}<div class="assessment-options">${q.options.map((o,i)=>`<button class="assessment-option" data-assess="${i}">${o}</button>`).join('')}</div><button class="btn btn-primary" id="assessNext" disabled>下一题</button>`;if(q.say)$('#assessListen').onclick=()=>speak(q.say);$$('[data-assess]').forEach(b=>b.onclick=()=>{assessChoice=+b.dataset.assess;$$('[data-assess]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#assessNext').disabled=false});$('#assessNext').onclick=()=>{if(assessChoice===q.a)assessScore++;assessIndex++;assessChoice=null;renderAssessment()}}
function finishAssessment(){const level=assessScore>=5?'Explorer':assessScore>=3?'Sprout':'Seed',meta=PROGRAM.levels.find(l=>l.id===level);$('#assessBar').style.width='100%';$('#assessmentContent').innerHTML=`<div class="assessment-result"><div class="seed-mark">${assessScore}/6</div><p class="eyebrow">推荐起点</p><h2>${meta.name}阶段</h2><p>${meta.goal}</p><p class="muted">测评只决定起点，之前的课程仍可在成长地图中自由练习。</p><button class="btn btn-primary" id="enterLand">进入 Zianna Land</button></div>`;$('#enterLand').onclick=()=>{state.profile={name:'Zianna',level,assessedAt:day(),score:assessScore};state.daily={};saveState();$('#assessmentLayer').hidden=true;renderAll();toast('专属学习路径已经准备好')}}

function renderLibrary(){const read=Object.keys(state.reading).length;$('#libraryProgress').innerHTML=`<strong>${read} / ${READERS.length}</strong><span>已完成</span>`;const levels=[['all','全部'],['Seed','种子'],['Sprout','新芽'],['Explorer','探索者']];$('#readerFilters').innerHTML=levels.map(x=>`<button class="filter ${readerFilter===x[0]?'active':''}" data-reader-filter="${x[0]}">${x[1]}</button>`).join('');const list=readerFilter==='all'?READERS:READERS.filter(r=>r.level===readerFilter);$('#readerGrid').innerHTML=list.map(r=>{const done=state.reading[r.id];return `<button class="reader-card ${done?'done':''}" data-reader="${r.id}"><span class="book-no">W${String(r.week).padStart(2,'0')}</span><small>${r.series} · ${r.level} · ${r.minutes} MIN</small><h3>${r.title}</h3><p>${r.text.split(' ').slice(0,12).join(' ')}…</p><b>${done?`已读完 · ${done.score}%`:'打开阅读 →'}</b></button>`}).join('');$$('[data-reader-filter]').forEach(b=>b.onclick=()=>{readerFilter=b.dataset.readerFilter;renderLibrary()});$$('[data-reader]').forEach(b=>b.onclick=()=>openReader(b.dataset.reader))}
function highlightReader(r){const known=new Set(r.words.map(x=>x.toLowerCase()));return r.text.split(/(\s+)/).map(token=>{const clean=token.toLowerCase().replace(/[^a-z']/g,'');return known.has(clean)?`<button class="tap-word" data-read-word="${clean}">${token}</button>`:token}).join('')}
function openReader(id){currentReader=READERS.find(r=>r.id===id);if(!currentReader)return;readerPassed=false;state.lastView='library';nav('reader');$('#readerMeta').textContent=`${currentReader.series} · WEEK ${currentReader.week} · ${currentReader.level}`;$('#readerTitle').textContent=currentReader.title;$('#readerText').innerHTML=highlightReader(currentReader);$('#readerCn').textContent=currentReader.cn;$('#readerCn').hidden=true;$('#readerToggleCn').textContent='显示阅读提示';$('#readerQuestion').textContent=currentReader.question;$('#readerResult').textContent='';$('#readerChoices').innerHTML=currentReader.options.map((o,i)=>`<button class="choice" data-reader-choice="${i}">${o}</button>`).join('');$('#finishReader').disabled=true;$('#readerRecordMessage').textContent='';$('#readerRecordPreview').hidden=true;$$('[data-read-word]').forEach(b=>b.onclick=()=>speak(b.dataset.readWord,.72));$$('[data-reader-choice]').forEach(b=>b.onclick=()=>{const answer=currentReader.options[+b.dataset.readerChoice];if(answer===currentReader.answer){readerPassed=true;b.classList.add('correct');$('#readerResult').textContent='读懂啦！现在可以完成阅读。';$('#finishReader').disabled=false}else{b.classList.add('wrong');$('#readerResult').textContent='回到短文找一找线索。'}})}
function finishReader(){if(!currentReader||!readerPassed)return;state.reading[currentReader.id]={completedAt:day(),score:100};state.activity.push({date:day(),readerId:currentReader.id,week:currentReader.week,skill:'reading',score:100,mastered:true,minutes:currentReader.minutes,mode:'reader'});saveState();toast('一本新读物加入了 Zianna 的书架！');setTimeout(()=>nav('library'),550)}
async function recordReader(){if(mediaRecorder?.state==='recording'){mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){toast('当前浏览器不能录音，可以继续完成阅读');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>recordChunks.push(e.data);mediaRecorder.onstop=async()=>{const blob=new Blob(recordChunks,{type:mediaRecorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);$('#readerRecordPreview').src=url;$('#readerRecordPreview').hidden=false;$('#readerRecord').textContent='重新录制';stream.getTracks().forEach(t=>t.stop());await saveArtifact({id:`reader-${currentReader.id}-${Date.now()}`,readerId:currentReader.id,week:currentReader.week,date:day(),title:`有声书 · ${currentReader.title}`,blob});$('#readerRecordMessage').textContent='有声书已保存在这台设备。'};mediaRecorder.start();$('#readerRecord').textContent='停止并保存';$('#readerRecordMessage').textContent='正在录制你的旁白…'}catch{$('#readerRecordMessage').textContent='没有获得麦克风权限，可以继续完成阅读。'}}

function last7(){const start=new Date();start.setDate(start.getDate()-6);start.setHours(0,0,0,0);return state.activity.filter(x=>new Date(x.date+'T12:00:00')>=start)}
async function renderReport(){const rows=last7(),mastered=Object.values(state.records).filter(r=>r.mastered).length,minutes=rows.reduce((n,x)=>n+x.minutes,0),days=new Set(rows.map(x=>x.date)).size,books=Object.keys(state.reading).length;$('#reportStats').innerHTML=[['本周学习',`${days} 天`],['投入时间',`${minutes} 分钟`],['掌握课程',`${mastered} 课`],['读完小书',`${books} 本`]].map(x=>`<article class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('');const skillNames={listening:'听力',phonics:'拼读',sentence:'句子',reading:'阅读',speaking:'表达'},skills=['listening','phonics','sentence','reading','speaking'];$('#skillReport').innerHTML=skills.map(s=>{const data=rows.filter(x=>x.skill===s),score=data.length?Math.round(data.reduce((n,x)=>n+x.score,0)/data.length):0;return `<div class="skill-row"><span>${skillNames[s]}</span><div class="bar"><span style="width:${score}%"></span></div><b>${score||'—'}</b></div>`}).join('')+`<p class="adaptive-note">系统当前采用：${adaptiveCopy()}</p>`;const weekDone=PROGRAM.weeks.filter(w=>w.units.some(u=>state.records[u.id]));$('#canDoReport').innerHTML=weekDone.length?weekDone.slice(-3).map(w=>`<p>✓ ${w.canDo}</p>`).join(''):'<p class="muted">完成第一课后，这里会出现具体的能力描述。</p>';await renderArtifacts();renderParentAdvice()}

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('ziannaLandDB',1);req.onupgradeneeded=()=>req.result.createObjectStore('artifacts',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveArtifact(item){try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('artifacts','readwrite');tx.objectStore('artifacts').put(item);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch{toast('录音可以播放，但这次没有保存成功')}}
async function getArtifacts(){try{const db=await openDB(),items=await new Promise((resolve,reject)=>{const r=db.transaction('artifacts').objectStore('artifacts').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return items}catch{return []}}
async function renderArtifacts(){const items=(await getArtifacts()).sort((a,b)=>b.id.localeCompare(a.id));$('#artifactList').innerHTML=items.length?items.map((x,i)=>`<article class="artifact"><strong>${x.title}</strong><small class="muted">${x.date}</small><audio controls src="${URL.createObjectURL(x.blob)}"></audio></article>`).join(''):'<p class="muted">完成每周表达任务并录音后，作品会保存在这里。</p>'}
function exportData(){const blob=new Blob([JSON.stringify({program:PROGRAM.version,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`zianna-land-${day()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function resetData(){if(!confirm('确定清除这台设备上的测评与学习记录吗？声音作品也会删除。'))return;localStorage.removeItem(STORE);try{indexedDB.deleteDatabase('ziannaLandDB')}catch{}state={...blankState,records:{},reading:{},dialogues:{},daily:{},activity:[]};startAssessment()}
function renderAll(){renderHome();renderCoachCard();renderCourse();renderDialogueHub();renderLibrary();renderReport();$('#levelPill').textContent=`${levelName()}阶段`}

$$('[data-nav]').forEach(b=>b.onclick=e=>{e.preventDefault();nav(b.dataset.nav)});$('#startToday').onclick=()=>{const item=todayPlan().find(x=>!planDone(x))||todayPlan()[0];openLesson(item.unit.id,item.mode)};$('#backFromLesson').onclick=()=>nav(['course','library'].includes(state.lastView)?state.lastView:'home');$('#listenStory').onclick=()=>speak(current.story);$('#listenPattern').onclick=()=>speak(current.pattern,.8);$('#playDialogue').onclick=()=>{speak(weekFor(current).dialogue,.78);$('#storyStage').classList.remove('playing');void $('#storyStage').offsetWidth;$('#storyStage').classList.add('playing')};$('#toggleLessonCn').onclick=()=>{const el=$('#lessonCn');el.hidden=!el.hidden;$('#toggleLessonCn').textContent=el.hidden?'显示中文提示':'隐藏中文提示'};$('#markSpoken').onclick=markSpoken;$('#recordWork').onclick=recordWork;$('#finishLesson').onclick=finishLesson;$('#practiceAgain').onclick=()=>{challengePassed=false;challengePoints=0;challengeAttempts=0;spoken=false;$('#markSpoken').textContent='我已经说了一遍';renderChallenge();updateFinish()};$('#backFromReader').onclick=()=>nav('library');$('#readerListen').onclick=()=>speak(currentReader.text,.76);$('#readerToggleCn').onclick=()=>{const el=$('#readerCn');el.hidden=!el.hidden;$('#readerToggleCn').textContent=el.hidden?'显示阅读提示':'隐藏阅读提示'};$('#finishReader').onclick=finishReader;$('#readerRecord').onclick=recordReader;$('#reassess').onclick=startAssessment;$('#exportData').onclick=exportData;$('#resetData').onclick=resetData;
$('#lessonVideo').onloadedmetadata=()=>{$('#videoFallback').hidden=true};$('#lessonVideo').onerror=()=>{$('#videoFallback').hidden=false;$('#videoFallback').innerHTML='视频暂时没有加载成功<br><small>可以继续完成下面的听读与互动</small>'};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installApp').hidden=false});$('#installApp').onclick=async()=>{if(!installPrompt)return toast('请使用浏览器菜单安装到设备');installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installApp').hidden=true};
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js');
renderAll();if(!state.profile)startAssessment();

function recommendedTalk(){return DIALOGUES[(activeWeek()?.units[0].week||1)-1]||DIALOGUES[0]}
function renderCoachCard(){const talk=recommendedTalk();if(!talk||!$('#coachCard'))return;const done=state.dialogues[talk.id];$('#coachCard').innerHTML=`<p class="eyebrow">AI ROLE PLAY · ${talk.guide}</p><h3>${talk.title}</h3><p>${talk.mission}</p><div class="coach-card-bottom"><span>${done?`上次 ${done.score}% · ${done.missing?.length?'有目标词待练':'关键表达完整'}`:'3 轮 · 约 5 分钟'}</span><button class="btn btn-forest" data-home-talk="${talk.id}">${done?'再练一次':'开始对话'}</button></div>`;$('[data-home-talk]').onclick=e=>openTalk(e.currentTarget.dataset.homeTalk)}
function renderDialogueHub(){if(!DIALOGUES.length)return;const recommended=recommendedTalk();$('#coachRecommendation').textContent=`${recommended.guide} 推荐：${recommended.title}`;$('#coachRecommendationText').textContent=`正在学习 Week ${recommended.week}，今天重点练习：${recommended.mission}`;$('#startRecommendedTalk').dataset.talk=recommended.id;$('#talkGrid').innerHTML=DIALOGUES.map(t=>{const result=state.dialogues[t.id],current=t.id===recommended.id;return `<button class="talk-card ${current?'recommended':''} ${result?'done':''}" data-talk="${t.id}"><span class="talk-week">W${String(t.week).padStart(2,'0')}</span><small>${t.guide} · ${t.level}</small><h3>${t.title}</h3><p>${t.mission}</p><b>${result?`${result.score}% · ${result.missing?.length?'继续练':'已完成'}`:current?'今日推荐 →':'开始对话 →'}</b></button>`}).join('');$$('[data-talk]').forEach(b=>b.onclick=()=>openTalk(b.dataset.talk))}
function openTalk(id){currentTalk=DIALOGUES.find(t=>t.id===id);if(!currentTalk)return;talkTurn=0;talkResults=[];state.lastView='dialogue';nav('coach');$('#coachMeta').textContent=`WEEK ${currentTalk.week} · ${currentTalk.guide} COACH`;$('#coachTitle').textContent=currentTalk.title;$('#coachMission').textContent=currentTalk.mission;$('#coachResult').hidden=true;$('#coachReply').hidden=false;renderTalkTurn()}
function renderTalkTurn(){const turn=currentTalk.turns[talkTurn];$('#coachProgressBar').style.width=`${talkTurn/currentTalk.turns.length*100}%`;const history=talkResults.map(r=>`<div class="chat-row child"><span>Zianna</span><p>${escapeHtml(r.answer)}</p></div><div class="chat-row guide"><span>${currentTalk.guide}</span><p>${r.feedback}</p></div>`).join('');$('#coachChat').innerHTML=`${history}<div class="chat-row guide current"><span>${currentTalk.guide}</span><p>${turn.prompt}</p><button class="chat-listen" data-chat-listen>♪ 听问题</button></div>`;$('#coachInput').value='';$('#coachTargets').innerHTML=turn.expected.map(x=>`<span>${x}</span>`).join('');$('#coachSuggestions').innerHTML=turn.suggestions.map(x=>`<button data-suggestion>${x}</button>`).join('');$('[data-chat-listen]').onclick=()=>speak(turn.prompt,.78);$$('[data-suggestion]').forEach(b=>b.onclick=()=>{$('#coachInput').value=b.textContent;$('#coachInput').focus()});$('#coachMicNote').textContent='也可以先大声说，再输入或选择最接近的回答。';$('#coachSubmit').disabled=false;setTimeout(()=>speak(turn.prompt,.78),250)}
function escapeHtml(text){const el=document.createElement('div');el.textContent=text;return el.innerHTML}
function analyseAnswer(answer,turn){const normalized=answer.toLowerCase().replace(/[^a-z'\s]/g,' ').replace(/\s+/g,' ').trim(),found=turn.expected.filter(x=>normalized.includes(x.toLowerCase())),missing=turn.expected.filter(x=>!found.includes(x));const score=turn.expected.length>2?(found.length?100:40):Math.max(40,Math.round(found.length/turn.expected.length*100));return {found,missing,score}}
function submitTalk(){const answer=$('#coachInput').value.trim();if(!answer)return toast('先说出、输入或选择一句英语回答');const turn=currentTalk.turns[talkTurn],analysis=analyseAnswer(answer,turn),hit=analysis.found.length>0,feedback=hit?turn.followupHit:`${turn.followupMiss} 你已经完成了这一轮，我们再往前一步。`;talkResults.push({prompt:turn.prompt,answer,...analysis,feedback});$('#coachSubmit').disabled=true;speak(feedback,.8);talkTurn++;if(talkTurn<currentTalk.turns.length){setTimeout(renderTalkTurn,500)}else{setTimeout(finishTalk,500)}}
function finishTalk(){const score=Math.round(talkResults.reduce((n,x)=>n+x.score,0)/talkResults.length),missing=[...new Set(talkResults.flatMap(x=>x.missing))],found=[...new Set(talkResults.flatMap(x=>x.found))],old=state.dialogues[currentTalk.id]||{};state.dialogues[currentTalk.id]={completedAt:day(),updatedAt:new Date().toISOString(),score,missing,found,attempts:(old.attempts||0)+1};state.activity.push({date:day(),dialogueId:currentTalk.id,week:currentTalk.week,skill:'speaking',score,mastered:score>=80,minutes:5,mode:'dialogue'});saveState();$('#coachProgressBar').style.width='100%';$('#coachReply').hidden=true;$('#coachResult').hidden=false;$('#coachResult').innerHTML=`<div class="result-orb">${score}%</div><p class="eyebrow">CONVERSATION COMPLETE</p><h2>${score>=80?'这次对话很完整！':'找到下一次要练的词了'}</h2><p>${missing.length?`建议再练：<b>${missing.join(' · ')}</b>`:`已经用到了本轮全部关键表达：${found.join(' · ')}`}</p><div class="lesson-actions"><button class="btn btn-soft" data-talk-again>再练一次</button><button class="btn btn-primary" data-talk-done>返回对话馆</button></div>`;$('[data-talk-again]').onclick=()=>openTalk(currentTalk.id);$('[data-talk-done]').onclick=()=>nav('dialogue');renderCoachCard();renderDialogueHub()}
function startSpeechAnswer(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('#coachMicNote').textContent='当前浏览器不支持语音转文字，请大声说完后输入或选择回答。';return}try{speechRecognition?.abort();speechRecognition=new Recognition();speechRecognition.lang='en-US';speechRecognition.interimResults=false;speechRecognition.maxAlternatives=1;speechRecognition.onstart=()=>{$('#coachSpeak').textContent='正在听…';$('#coachMicNote').textContent='请说一句完整的英语。浏览器可能需要联网完成识别。'};speechRecognition.onresult=e=>{$('#coachInput').value=e.results[0][0].transcript;$('#coachMicNote').textContent='已经听到这句话，可以检查后发送。'};speechRecognition.onerror=()=>{$('#coachMicNote').textContent='这次没有听清，可以再说一次或使用下方示例。'};speechRecognition.onend=()=>{$('#coachSpeak').textContent='麦克风回答'};speechRecognition.start()}catch{$('#coachMicNote').textContent='麦克风暂时不可用，可以继续输入或选择回答。'}}
function studyStreak(){const dates=[...new Set(state.activity.map(x=>x.date))].sort().reverse();let streak=0;for(let i=0;i<dates.length;i++){if(daysBetween(dates[i])===i)streak++;else break}return streak}
function renderParentAdvice(){if(!$('#parentAdvice'))return;const rows=last7(),talks=Object.values(state.dialogues),latest=[...talks].sort((a,b)=>(a.updatedAt||a.completedAt||'').localeCompare(b.updatedAt||b.completedAt||'')).at(-1),skillNames={listening:'听力',phonics:'拼读',sentence:'句子',reading:'阅读',speaking:'表达'},skillRows=['listening','phonics','sentence','reading','speaking'].map(skill=>({skill,rows:rows.filter(x=>x.skill===skill)})).filter(x=>x.rows.length).map(x=>({...x,avg:Math.round(x.rows.reduce((n,r)=>n+r.score,0)/x.rows.length)})).sort((a,b)=>a.avg-b.avg),weak=skillRows[0];const advice=[];if(!rows.length)advice.push('本周先完成 2 次十分钟日课，让系统获得足够数据后再调整难度。');else advice.push(`保持每次 10–12 分钟即可；当前连续学习 ${studyStreak()} 天，本周已投入 ${rows.reduce((n,x)=>n+x.minutes,0)} 分钟。`);if(weak)advice.push(`${skillNames[weak.skill]}目前约 ${weak.avg}%：下次优先完成系统安排的复习，不需要额外加量。`);if(latest?.missing?.length)advice.push(`角色对话中遗漏了 “${latest.missing.slice(0,3).join(' / ')}”：睡前用其中一个词造一句话即可。`);else if(talks.length)advice.push('最近一次角色对话关键表达完整，可以尝试关闭中文提示后再说一遍。');else advice.push(`建议从“${recommendedTalk().title}”开始一次三轮对话，观察孩子能否独立回答。`);$('#dialogueStat').textContent=`已完成 ${talks.length} / ${DIALOGUES.length} 个对话主题`;$('#parentAdvice').innerHTML=advice.map((x,i)=>`<article class="advice-item"><b>0${i+1}</b><p>${x}</p></article>`).join('')}

$('#startRecommendedTalk').onclick=e=>openTalk(e.currentTarget.dataset.talk);$('#backFromCoach').onclick=()=>nav('dialogue');$('#coachSubmit').onclick=submitTalk;$('#coachSpeak').onclick=startSpeechAnswer;




